django_nested_formset_mwe/django_nested_formset_mwe/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import reverse
from django.views.generic import RedirectView

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^', include('myapp.urls')),
]

django_nested_formset_mwe/myapp/urls.py
from django.conf.urls import url
from django.urls import reverse
from django.views.generic import RedirectView

from . import views

app_name = 'myapp'
urlpatterns = [
    url(r'^promotion/(?P<pk>\d+)/edit$', views.PromotionUpdateView.as_view(), name='promotion-edit'),
    url(r'^promotion/(?P<pk>\d+)/$', views.PromotionDetailView.as_view(), name='promotion-detail'),
    url(r'^promotion/create/$', views.PromotionCreateView.as_view(), name='promotion-create'),
    url(r'^promotion/$', views.PromotionListView.as_view(), name='promotion-list'),
    url(r'^$', RedirectView.as_view(url='promotion/', permanent=False), name='index')
]

django_nested_formset_mwe/myapp/models.py
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class Promotion(models.Model):
    year = models.IntegerField(
        verbose_name=_('year_label'),
        help_text=_('year_help_text'),
    )
    name = models.CharField(
        verbose_name=_('name_label'),
        help_text=_('name_help_text'),
        max_length=64,
    )

    def __str__(self):
        return "Promotion %i (%s)" % (self.year, self.name)

    def get_absolute_url(self):
        return reverse('myapp:promotion-detail', kwargs={'pk': self.pk})


class Student(models.Model):
    promotion = models.ForeignKey(
        to=Promotion,
        verbose_name=_('promotion_label'),
        help_text=_('promotion_help_text'),
        on_delete=models.CASCADE,
        related_name='students',
    )
    first_name = models.CharField(
        verbose_name=_('first_name_label'),
        help_text=_('first_name_help_text'),
        max_length=64,
    )
    last_name = models.CharField(
        verbose_name=_('last_name_label'),
        help_text=_('last_name_help_text'),
        max_length=64,
    )

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)


class Address(models.Model):
    student = models.ForeignKey(
        to=Student,
        verbose_name=_('first_name_label'),
        help_text=_('first_name_help_text'),
        on_delete=models.CASCADE,
        related_name='addresses',
    )
    full_address = models.CharField(
        verbose_name=_('full_address_label'),
        help_text=_('full_address_help_text'),
        max_length=256,
    )
    main_address = models.BooleanField(
        verbose_name=_('main_address_label'),
        help_text=_('main_address_help_text'),
        default=False,
    )

    def __str__(self):
        return  self.full_address

django_nested_formset_mwe/myapp/forms.py
"""
iPPI-DB django forms
"""
import itertools
from collections import OrderedDict

from django import forms
from django.forms import ModelForm, inlineformset_factory
from django.utils.translation import ugettext_lazy as _, ugettext

from myapp import models


class BaseInlineNestedFormSet(forms.BaseInlineFormSet):
    def add_fields(self, form, index):
        super().add_fields(form, index)
        delete_field = form.fields.pop('DELETE')
        delete_field.widget.attrs["onclick"] = "delete_button_clicked(this)"
        delete_field.widget.attrs["class"] = delete_field.widget.attrs.get("class", "") + " formset-item-delete"
        delete_field.label = _("DELETE_label")
        delete_help_text = ugettext("DELETE_help_text")
        if delete_help_text != "DELETE_help_text":
            delete_field.help_text = delete_help_text
        form.fields = OrderedDict(
            itertools.chain([('DELETE', delete_field)], form.fields.items())
        )

    def is_valid(self):
        result = super().is_valid()

        if self.is_bound:
            for form in self.forms:
                result = result and form.is_valid()
                if hasattr(form, 'nested'):
                    result = result and form.nested.is_valid()

        return result

    def save(self, commit=True):
        result = super().save(commit=commit)

        for form in self.forms:
            if hasattr(form, 'nested'):
                if not self._should_delete_form(form):
                    form.nested.save(commit=commit)
        return result


class AddressForm(ModelForm):
    class Meta:
        model = models.Address
        fields = '__all__'

    # Even if we set the field to required in the model they are not in the html form. Its an intended feature of the
    # formset which allow you to add new formset item but not use it, and also use the DELETE checkbox
    # without having the browser indicating the user that the field must be field.
    # uncomment hereafter and you will see
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields["full_address"].widget.attrs["required"] = True


class PromotionForm(ModelForm):
    class Meta:
        model = models.Promotion
        fields = '__all__'


AddressInlineFormset = inlineformset_factory(
    parent_model=models.Student,
    model=models.Address,
    form=AddressForm,
    formset=BaseInlineNestedFormSet,
    # fields='__all__',
    extra=1,
    # min_num=1,# using the min_num is tempting, but with an nested inlined formset it does not work:
    # # it wants to have at least on address which is obsiouly empty when we check the DELETE of its empty student
    # # it make the formset being invalid. Prefer an extra=1, an in case of server side validation.
    # validate_min=True,
    can_delete=True,
)


class BaseStudentFormset(BaseInlineNestedFormSet):
    def add_fields(self, form, index):
        super().add_fields(form, index)
        form.nested = AddressInlineFormset(
            instance=form.instance,
            data=form.data if form.is_bound else None,
            files=form.files if form.is_bound else None,
            # set the prefix to distinguish the nested formset one from the other.
            prefix='addresses-%s-%s' % (
                form.prefix,
                AddressInlineFormset.get_default_prefix()
            ),
        )

    def full_clean(self):
        """
        An example of validation across the whole formset, here no homonym.
        """

        super().full_clean()
        if not self.is_bound:  # Stop further processing.
            return
        names = set()
        for form in self.forms:
            if form.cleaned_data.get("DELETE", False):
                continue

            # if the form is empty
            if not (form.has_changed() or 'first_name' in form.cleaned_data or 'last_name' in form.cleaned_data):
                continue

            name = form.cleaned_data['first_name'] + "__" + form.cleaned_data['last_name']
            if name in names:
                message = _("Student must be distinct. Incriminated entry:'%(first_name)s %(last_name)s'") % dict(
                    first_name=form.cleaned_data['first_name'],
                    last_name=form.cleaned_data['last_name']
                )
                self._non_form_errors.append(message)
                form.errors.setdefault('first_name', []).append(message)
                form.errors.setdefault('last_name', []).append(message)
            names.add(name)


StudentInlineFormset = inlineformset_factory(
    parent_model=models.Promotion,
    model=models.Student,
    formset=BaseStudentFormset,
    fields='__all__',
    extra=0,
    min_num=1,  # here you can use it
    validate_min=True,
    can_delete=True,
)

django_nested_formset_mwe/myapp/views.py
from django.db import transaction
from django.views.generic import DetailView, ListView, UpdateView, CreateView
from django.views.generic.edit import FormMixin

from myapp import models, forms


class EmbededFormsetMixin(FormMixin):
    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data['formset'] = forms.StudentInlineFormset(self.request.POST, instance=self.object)
        else:
            data['formset'] = forms.StudentInlineFormset(instance=self.object)
        return data

    def form_valid(self, form):
        with transaction.atomic():
            self.object = form.save()
            # form.instance = self.object
            context = self.get_context_data()
            formset = context['formset']

            if formset.is_valid():
                formset.instance = self.object
                formset.save()
            else:
                return super().form_invalid(form)
        return super().form_valid(form)


class PromotionUpdateView(EmbededFormsetMixin, UpdateView):
    model = models.Promotion
    fields = '__all__'


class PromotionDetailView(DetailView):
    model = models.Promotion


class PromotionListView(ListView):
    model = models.Promotion


class PromotionCreateView(EmbededFormsetMixin, CreateView):
    model = models.Promotion
    fields = '__all__'

django_nested_formset_mwe/myapp/templates/myapp/formset-nested-form.html
{% load crispy_forms_tags %}
{% load my_bootstrap_tags %}

<div class="card mb-4">
    <div class="card-body formset-item">
        {{ form|crispy }}

        {% if form.nested %}
        {{ form.nested.management_form }}
        {{ form.nested.non_form_errors|as_bootstrap_alert }}

        {% if nested_form %}
        <div class="card mb-4 formset-nested-item">
            <div class="card-body mb-4">
                {{ nested_form|crispy }}
            </div>
        </div>
        {% endif %}
        {% for nested_form in form.nested.forms %}
        <div class="card mb-4 formset-nested-item">
            <div class="card-body mb-4">
                {{ nested_form|crispy }}
            </div>
        </div>
        {% endfor %}
        <div class="card mb-4 form-group">
            <button
                    type="button"
                    class="btn btn-default float-left"
                    onclick="add_nested_form_to_nested_formset(this,'{{form.nested.prefix}}','{{parent_prefix}}');"
            >{{add_another_nested_one}}
            </button>
        </div>
        {% endif %}
    </div>
</div>

django_nested_formset_mwe/myapp/templates/myapp/formset-nested-formset.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load my_bootstrap_tags %}
{% load static %}

{%block extrajs%}
<script src="{% static '/js/formset-nested-formset.js'%}"></script>
{%endblock extrajs%}

{%block extracss%}
<link rel="stylesheet" href="{% static '/css/formset-nested-formset.css' %}">
{%endblock extracss%}


{%block content%}
<div class="col-12 mb-4 formset-container">
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{form|crispy}}
        {% if formset is not None %}
            {{ formset.management_form }}
            {{ formset.non_form_errors|as_bootstrap_alert }}
            {% for form in formset.forms %}
            {% include "myapp/formset-nested-form.html" with form=form nested_forms=form.nested.forms nested_form=None add_another_nested_one="Add another one" parent_prefix=formset.prefix %}
        {% endfor %}
        <div class="col-12 mb-4">
            <button
                    type="button"
                    class="btn btn-default"
                    onclick="add_form_to_nested_formset(this,'{{formset.prefix}}');"
            >Add another {%block parent_kind%}one{%endblock%}
            </button>
            <button type="submit" class="btn btn-success float-right">Save all</button>
        </div>
        {%endif%}
    </form>
    {% block emptyform %}
        {%if formset is not None %}
        <div class="card mb-4 bg-warning">
            <div class="card-header">
                Here is the empty formset, usually you have a css code somewhere saying
                <code>.empty_form{display:none;}</code>
            </div>
            <div class="card-body empty_form" style="display:noneXXX">
                {% include "myapp/formset-nested-form.html" with form=formset.empty_form nested_forms=formset.empty_form.nested.forms nested_form=formset.empty_form.nested.empty_form add_another_nested_one="Add another one" parent_prefix=formset.prefix %}
            </div>
        </div>
        {%endif%}
    {% endblock emptyform%}
</div>
{%endblock content%}

django_nested_formset_mwe/myapp/templates/myapp/promotion_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{%block title%}
Promotion {{promotion.year}} <i>{{promotion.name}} </i>
{%endblock title%}

{%block content%}
{% for student in object.students.all %}
<div class="col-sm-6 col-md-4 col-lg-3 mb-4">
    <div class="card">
        <div class="card-header">{{student}}</div>
        <div class="card-body">
            <ul>
                {% for address in student.addresses.all %}
                <li>
                    {{address.full_address}}
                    {% if address.main_address %}
                    (main address)
                    {%endif%}
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endfor %}
<div class="col-12 mb-4">
    <a role="button" class="btn btn-info float-right" href="{% url 'myapp:promotion-edit' pk=promotion.pk%}">
        Edit information
    </a>
    <a role="button" class="btn btn-info" href="{% url 'myapp:promotion-list' %}">
        List
    </a>
</div>
{%endblock content%}

django_nested_formset_mwe/myapp/templates/myapp/promotion_form.html
{% extends "myapp/formset-nested-formset.html" %}

{%block title%}
{% if object is None %}
Creating a promotion along with its students and their addresses
{%else%}
{% if formset is None %}
Updating a promotion
{%else%}
Updating students for promotion {{object.year}} <i>{{object.name}}</i>
{%endif%}
{%endif%}
{%endblock title%}

{% block parent_kind%}student{%endblock%}
{% block nested_kind%}address{%endblock%}

django_nested_formset_mwe/myapp/templates/myapp/promotion_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{%block title%}
Promotions
{%endblock title%}
{%block content%}
{% for o in object_list %}
<div class="col-sm-6 col-md-4 col-lg-3 mb-4">
    <div class="card">
        <a href="{% url 'myapp:promotion-detail' pk=o.pk%}" class="card-header">{{o}}</a>
        <div class="card-body">
            Has {{o.students.count}} students
        </div>
    </div>
</div>
{% endfor %}
<div class="col-12 mb-4">
    <a role="button" class="btn btn-info float-right" href="{% url 'myapp:promotion-create' %}">
        Create a new promotion
    </a>
</div>
{%endblock content%}

django_nested_formset_mwe/myapp/templates/myapp/promotion_manage_students.html
{% extends "myapp/formset-nested-formset.html" %}
{%block title%}
Updating students for promotion {{promotion.year}} <i>{{promotion.name}}</i>
{%endblock title%}


{% block parent_kind%}student{%endblock%}
{% block nested_kind%}address{%endblock%}